[versions]
android-appliication = "8.2.1"
appcompat = "1.6.1"
core-ktx = "1.12.0"
hilt-android = "2.50"
junit = "4.13.2"
kotlin-android = "1.9.22"
kotlinx-coroutines-android = "1.7.2"
ksp = "1.9.22-1.0.16"
lifecycle-viewmodel-ktx = "2.6.2"
material = "1.11.0"
navigation-fragment-ktx = "2.7.6"
preference-ktx = "1.2.1"
review-ktx = "2.0.1"
seismic = "1.0.3"
timber = "5.0.1"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "hilt-android" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-android" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
material = { module = "com.google.android.material:material", version.ref = "material" }
review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review-ktx" }
seismic = { module = "com.squareup:seismic", version.ref = "seismic" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-appliication" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin-android" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }