package com.banasiak.coinflip.common

import androidx.annotation.StringRes
import com.banasiak.coinflip.R
import com.banasiak.coinflip.common.EmojiGroup.ACTIVITIES
import com.banasiak.coinflip.common.EmojiGroup.ANIMALS
import com.banasiak.coinflip.common.EmojiGroup.FACES
import com.banasiak.coinflip.common.EmojiGroup.FOOD
import com.banasiak.coinflip.common.EmojiGroup.GESTURES
import com.banasiak.coinflip.common.EmojiGroup.OBJECTS
import com.banasiak.coinflip.common.EmojiGroup.SYMBOLS
import com.banasiak.coinflip.common.EmojiGroup.TRAVEL

/**
 * Which shelf of the picker an emoji sits on. Unicode's own top-level ordering, minus Flags.
 *
 * Declaration order is load-bearing in the same way [CoinGroup]'s is: `buildEmojiList` opens a
 * header only on a change of group, so the catalog has to stay in unbroken runs of these.
 */
enum class EmojiGroup(@param:StringRes val label: Int) {
  FACES(R.string.settings_item_emoji_group_faces),
  GESTURES(R.string.settings_item_emoji_group_gestures),
  ANIMALS(R.string.settings_item_emoji_group_animals),
  FOOD(R.string.settings_item_emoji_group_food),
  ACTIVITIES(R.string.settings_item_emoji_group_activities),
  TRAVEL(R.string.settings_item_emoji_group_travel),
  OBJECTS(R.string.settings_item_emoji_group_objects),
  SYMBOLS(R.string.settings_item_emoji_group_symbols)
}

/**
 * One emoji the picker offers.
 *
 * [glyph] is exactly one code point -- no variation selector, no zero-width joiner, no skin-tone
 * modifier, no regional-indicator pair. `EmojiCatalogTests` asserts it, and it is not cosmetic:
 * `Paint.hasGlyph` is only dependable for single code points, and a sequence a device cannot compose
 * lands on the coin as two glyphs side by side.
 *
 * [keywords] is a lowercase, space-separated, **untranslated** search bag, for the same reason
 * `CoinType.coinName` is a plain string: it was never translated, and holding it in Kotlin says so
 * outright where a `string-array` would leave every locale a permanent hole. Nobody is left without
 * a way to find one -- the grid, the group headers and the jump bar are language-free, and the
 * picker matches a pasted glyph too, so the system keyboard's own localized search reaches anything
 * the device can draw.
 */
data class Emoji(val glyph: String, val keywords: String, val group: EmojiGroup)

/**
 * Every emoji the picker offers, in Unicode's own order within each group so the grid reads the way
 * the user's keyboard does.
 *
 * Curation rules, so the next person extending this does not have to re-derive them:
 * - **Exactly one code point.** That one clause bars U+FE0F, ZWJ sequences, skin-tone modifiers,
 *   keycaps and regional-indicator flags together.
 * - `Emoji_Presentation=Yes`, so the text-default dingbats do not arrive monochrome.
 * - **Emoji 5.0 (2017) or earlier**: that is the set Android 8.0 shipped, and 8.0 is `minSdk`.
 *   `Paint.hasGlyph` filters again at runtime, for the OEM fonts that ship their own.
 * - Nothing that is mostly lettering or mostly a rectangle -- it reads as a button, not a coin.
 * - Flags are out. They would fail the first rule anyway, but they are also rectangular and
 *   geopolitically loaded.
 */
object EmojiCatalog {
  val entries: List<Emoji> =
    listOf(
      // ----- FACES -----
      Emoji("😀", "grinning face happy smile", FACES),
      Emoji("😃", "grinning face big eyes happy", FACES),
      Emoji("😄", "grinning face smiling eyes happy", FACES),
      Emoji("😁", "beaming face grin smile", FACES),
      Emoji("😆", "grinning squinting laugh", FACES),
      Emoji("😅", "grinning sweat nervous laugh", FACES),
      Emoji("🤣", "rolling on the floor laughing rofl", FACES),
      Emoji("😂", "face with tears of joy laughing cry", FACES),
      Emoji("🙂", "slightly smiling face", FACES),
      Emoji("🙃", "upside down face silly", FACES),
      Emoji("😉", "winking face wink", FACES),
      Emoji("😊", "smiling face smiling eyes blush", FACES),
      Emoji("😇", "smiling face halo angel", FACES),
      Emoji("😍", "smiling face heart eyes love", FACES),
      Emoji("😘", "face blowing a kiss", FACES),
      Emoji("😗", "kissing face", FACES),
      Emoji("😚", "kissing face closed eyes", FACES),
      Emoji("😋", "face savoring food yum tongue", FACES),
      Emoji("😛", "face with tongue", FACES),
      Emoji("😜", "winking face with tongue", FACES),
      Emoji("🤪", "zany face crazy", FACES),
      Emoji("😝", "squinting face with tongue", FACES),
      Emoji("🤑", "money mouth face rich", FACES),
      Emoji("🤗", "hugging face hug", FACES),
      Emoji("🤭", "face with hand over mouth oops", FACES),
      Emoji("🤫", "shushing face quiet", FACES),
      Emoji("🤔", "thinking face hmm", FACES),
      Emoji("🤐", "zipper mouth face secret", FACES),
      Emoji("🤨", "face with raised eyebrow skeptical", FACES),
      Emoji("😐", "neutral face", FACES),
      Emoji("😑", "expressionless face", FACES),
      Emoji("😶", "face without mouth", FACES),
      Emoji("😏", "smirking face smug", FACES),
      Emoji("😒", "unamused face", FACES),
      Emoji("🙄", "face with rolling eyes", FACES),
      Emoji("😬", "grimacing face awkward", FACES),
      Emoji("🤥", "lying face liar pinocchio", FACES),
      Emoji("😌", "relieved face", FACES),
      Emoji("😔", "pensive face sad", FACES),
      Emoji("😴", "sleeping face asleep zzz", FACES),
      Emoji("🤤", "drooling face", FACES),
      Emoji("😷", "face with medical mask sick", FACES),
      Emoji("🤒", "face with thermometer sick fever", FACES),
      Emoji("🤕", "face with head bandage hurt", FACES),
      Emoji("🤢", "nauseated face sick green", FACES),
      Emoji("🤮", "face vomiting sick puke", FACES),
      Emoji("🤧", "sneezing face", FACES),
      Emoji("🤯", "exploding head mind blown", FACES),
      Emoji("🤠", "cowboy hat face", FACES),
      Emoji("😎", "smiling face with sunglasses cool", FACES),
      Emoji("🤓", "nerd face glasses", FACES),
      Emoji("🧐", "face with monocle", FACES),
      Emoji("😕", "confused face", FACES),
      Emoji("😟", "worried face", FACES),
      Emoji("🙁", "slightly frowning face", FACES),
      Emoji("😮", "face with open mouth surprised", FACES),
      Emoji("😯", "hushed face", FACES),
      Emoji("😲", "astonished face shocked", FACES),
      Emoji("😳", "flushed face embarrassed", FACES),
      Emoji("😨", "fearful face scared", FACES),
      Emoji("😰", "anxious face with sweat", FACES),
      Emoji("😥", "sad but relieved face", FACES),
      Emoji("😢", "crying face tear sad", FACES),
      Emoji("😭", "loudly crying face sobbing", FACES),
      Emoji("😱", "face screaming in fear", FACES),
      Emoji("😖", "confounded face", FACES),
      Emoji("😣", "persevering face", FACES),
      Emoji("😞", "disappointed face", FACES),
      Emoji("😩", "weary face", FACES),
      Emoji("😫", "tired face", FACES),
      Emoji("😤", "face with steam from nose triumph", FACES),
      Emoji("😡", "pouting face angry mad", FACES),
      Emoji("😠", "angry face mad", FACES),
      Emoji("🤬", "face with symbols on mouth cursing swearing", FACES),
      Emoji("😈", "smiling face with horns devil imp", FACES),
      Emoji("👿", "angry face with horns devil", FACES),
      Emoji("💀", "skull dead", FACES),
      Emoji("💩", "pile of poo", FACES),
      Emoji("🤡", "clown face", FACES),
      Emoji("👹", "ogre monster", FACES),
      Emoji("👺", "goblin", FACES),
      Emoji("👻", "ghost boo", FACES),
      Emoji("👽", "alien", FACES),
      Emoji("🤖", "robot", FACES),
      Emoji("🎃", "jack o lantern pumpkin halloween", FACES),
      Emoji("🎅", "santa claus christmas", FACES),
      Emoji("🤶", "mrs claus christmas", FACES),
      Emoji("🧙", "mage wizard", FACES),
      Emoji("🧚", "fairy", FACES),
      Emoji("🧛", "vampire", FACES),
      Emoji("🧜", "merperson mermaid", FACES),
      Emoji("🧝", "elf", FACES),
      Emoji("🧞", "genie", FACES),
      Emoji("🧟", "zombie", FACES),
      Emoji("😺", "grinning cat", FACES),
      Emoji("😹", "cat with tears of joy", FACES),
      Emoji("😻", "smiling cat heart eyes", FACES),
      Emoji("😼", "cat with wry smile", FACES),
      Emoji("😽", "kissing cat", FACES),
      Emoji("🙀", "weary cat", FACES),
      Emoji("😿", "crying cat", FACES),
      Emoji("😾", "pouting cat", FACES),
      // ----- GESTURES -----
      Emoji("👋", "waving hand wave hello", GESTURES),
      Emoji("🤚", "raised back of hand", GESTURES),
      Emoji("🖖", "vulcan salute spock", GESTURES),
      Emoji("👌", "ok hand", GESTURES),
      Emoji("🤞", "crossed fingers luck", GESTURES),
      Emoji("🤟", "love you gesture", GESTURES),
      Emoji("🤘", "sign of the horns rock", GESTURES),
      Emoji("🤙", "call me hand shaka", GESTURES),
      Emoji("👈", "backhand index pointing left", GESTURES),
      Emoji("👉", "backhand index pointing right", GESTURES),
      Emoji("👆", "backhand index pointing up", GESTURES),
      Emoji("👇", "backhand index pointing down", GESTURES),
      Emoji("👍", "thumbs up like yes", GESTURES),
      Emoji("👎", "thumbs down dislike no", GESTURES),
      Emoji("✊", "raised fist", GESTURES),
      Emoji("👊", "oncoming fist punch", GESTURES),
      Emoji("🤛", "left facing fist", GESTURES),
      Emoji("🤜", "right facing fist", GESTURES),
      Emoji("✋", "raised hand stop", GESTURES),
      Emoji("👏", "clapping hands applause", GESTURES),
      Emoji("🙌", "raising hands celebrate", GESTURES),
      Emoji("👐", "open hands", GESTURES),
      Emoji("🤲", "palms up together", GESTURES),
      Emoji("🤝", "handshake deal", GESTURES),
      Emoji("🙏", "folded hands please thanks pray", GESTURES),
      Emoji("💪", "flexed biceps muscle strong", GESTURES),
      Emoji("💅", "nail polish manicure", GESTURES),
      Emoji("🤳", "selfie", GESTURES),
      Emoji("👂", "ear", GESTURES),
      Emoji("👃", "nose", GESTURES),
      Emoji("👀", "eyes look", GESTURES),
      Emoji("👄", "mouth lips", GESTURES),
      Emoji("👅", "tongue", GESTURES),
      Emoji("🧠", "brain", GESTURES),
      Emoji("👶", "baby", GESTURES),
      Emoji("👦", "boy", GESTURES),
      Emoji("👧", "girl", GESTURES),
      Emoji("👨", "man", GESTURES),
      Emoji("👩", "woman", GESTURES),
      Emoji("🧑", "person", GESTURES),
      Emoji("👴", "old man", GESTURES),
      Emoji("👵", "old woman", GESTURES),
      Emoji("🙋", "person raising hand", GESTURES),
      Emoji("🙆", "person gesturing ok", GESTURES),
      Emoji("🙅", "person gesturing no", GESTURES),
      Emoji("🤷", "person shrugging shrug", GESTURES),
      Emoji("🤦", "person facepalming facepalm", GESTURES),
      Emoji("💁", "person tipping hand", GESTURES),
      Emoji("🙇", "person bowing sorry", GESTURES),
      Emoji("🤵", "person in tuxedo", GESTURES),
      Emoji("👰", "person with veil bride", GESTURES),
      Emoji("🤰", "pregnant woman", GESTURES),
      Emoji("👮", "police officer", GESTURES),
      Emoji("👷", "construction worker", GESTURES),
      Emoji("💂", "guard", GESTURES),
      Emoji("👸", "princess", GESTURES),
      Emoji("🤴", "prince", GESTURES),
      Emoji("👼", "baby angel", GESTURES),
      // ----- ANIMALS -----
      Emoji("🐶", "dog face puppy", ANIMALS),
      Emoji("🐱", "cat face kitten", ANIMALS),
      Emoji("🐭", "mouse face", ANIMALS),
      Emoji("🐹", "hamster face", ANIMALS),
      Emoji("🐰", "rabbit face bunny", ANIMALS),
      Emoji("🦊", "fox face", ANIMALS),
      Emoji("🐻", "bear face", ANIMALS),
      Emoji("🐼", "panda face", ANIMALS),
      Emoji("🐨", "koala", ANIMALS),
      Emoji("🐯", "tiger face", ANIMALS),
      Emoji("🦁", "lion face", ANIMALS),
      Emoji("🐮", "cow face", ANIMALS),
      Emoji("🐷", "pig face", ANIMALS),
      Emoji("🐸", "frog face", ANIMALS),
      Emoji("🐵", "monkey face", ANIMALS),
      Emoji("🙈", "see no evil monkey", ANIMALS),
      Emoji("🙉", "hear no evil monkey", ANIMALS),
      Emoji("🙊", "speak no evil monkey", ANIMALS),
      Emoji("🐒", "monkey", ANIMALS),
      Emoji("🐔", "chicken", ANIMALS),
      Emoji("🐧", "penguin", ANIMALS),
      Emoji("🐦", "bird", ANIMALS),
      Emoji("🐤", "baby chick", ANIMALS),
      Emoji("🐣", "hatching chick", ANIMALS),
      Emoji("🐥", "front facing baby chick", ANIMALS),
      Emoji("🦆", "duck", ANIMALS),
      Emoji("🦅", "eagle", ANIMALS),
      Emoji("🦉", "owl", ANIMALS),
      Emoji("🦇", "bat", ANIMALS),
      Emoji("🐺", "wolf face", ANIMALS),
      Emoji("🐗", "boar", ANIMALS),
      Emoji("🐴", "horse face", ANIMALS),
      Emoji("🦄", "unicorn face", ANIMALS),
      Emoji("🐝", "honeybee bee", ANIMALS),
      Emoji("🐛", "bug caterpillar", ANIMALS),
      Emoji("🦋", "butterfly", ANIMALS),
      Emoji("🐌", "snail", ANIMALS),
      Emoji("🐞", "lady beetle ladybug", ANIMALS),
      Emoji("🐜", "ant", ANIMALS),
      Emoji("🦗", "cricket", ANIMALS),
      Emoji("🦂", "scorpion", ANIMALS),
      Emoji("🐢", "turtle", ANIMALS),
      Emoji("🐍", "snake", ANIMALS),
      Emoji("🦎", "lizard", ANIMALS),
      Emoji("🦖", "t rex dinosaur", ANIMALS),
      Emoji("🦕", "sauropod dinosaur", ANIMALS),
      Emoji("🐙", "octopus", ANIMALS),
      Emoji("🦑", "squid", ANIMALS),
      Emoji("🦐", "shrimp", ANIMALS),
      Emoji("🦀", "crab", ANIMALS),
      Emoji("🐡", "blowfish pufferfish", ANIMALS),
      Emoji("🐠", "tropical fish", ANIMALS),
      Emoji("🐟", "fish", ANIMALS),
      Emoji("🐬", "dolphin", ANIMALS),
      Emoji("🐳", "spouting whale", ANIMALS),
      Emoji("🐋", "whale", ANIMALS),
      Emoji("🦈", "shark", ANIMALS),
      Emoji("🐊", "crocodile", ANIMALS),
      Emoji("🐅", "tiger", ANIMALS),
      Emoji("🐆", "leopard", ANIMALS),
      Emoji("🦓", "zebra", ANIMALS),
      Emoji("🦍", "gorilla", ANIMALS),
      Emoji("🐘", "elephant", ANIMALS),
      Emoji("🦏", "rhinoceros", ANIMALS),
      Emoji("🐪", "camel", ANIMALS),
      Emoji("🐫", "two hump camel", ANIMALS),
      Emoji("🦒", "giraffe", ANIMALS),
      Emoji("🐄", "cow", ANIMALS),
      Emoji("🐎", "horse", ANIMALS),
      Emoji("🐖", "pig", ANIMALS),
      Emoji("🐑", "ewe sheep", ANIMALS),
      Emoji("🐐", "goat", ANIMALS),
      Emoji("🦌", "deer", ANIMALS),
      Emoji("🐕", "dog", ANIMALS),
      Emoji("🐈", "cat", ANIMALS),
      Emoji("🐓", "rooster", ANIMALS),
      Emoji("🦃", "turkey", ANIMALS),
      Emoji("🐇", "rabbit", ANIMALS),
      Emoji("🦔", "hedgehog", ANIMALS),
      Emoji("🐾", "paw prints", ANIMALS),
      Emoji("🌵", "cactus", ANIMALS),
      Emoji("🎄", "christmas tree", ANIMALS),
      Emoji("🌲", "evergreen tree", ANIMALS),
      Emoji("🌳", "deciduous tree", ANIMALS),
      Emoji("🌴", "palm tree", ANIMALS),
      Emoji("🌱", "seedling", ANIMALS),
      Emoji("🌿", "herb", ANIMALS),
      Emoji("🍀", "four leaf clover luck", ANIMALS),
      Emoji("🍃", "leaf fluttering in wind", ANIMALS),
      Emoji("🍂", "fallen leaf", ANIMALS),
      Emoji("🍁", "maple leaf", ANIMALS),
      Emoji("🌾", "sheaf of rice", ANIMALS),
      Emoji("💐", "bouquet flowers", ANIMALS),
      Emoji("🌷", "tulip", ANIMALS),
      Emoji("🌹", "rose", ANIMALS),
      Emoji("🥀", "wilted flower", ANIMALS),
      Emoji("🌺", "hibiscus", ANIMALS),
      Emoji("🌸", "cherry blossom sakura", ANIMALS),
      Emoji("🌼", "blossom", ANIMALS),
      Emoji("🌻", "sunflower", ANIMALS),
      // ----- FOOD -----
      Emoji("🍇", "grapes fruit", FOOD),
      Emoji("🍉", "watermelon fruit melon", FOOD),
      Emoji("🍊", "tangerine orange fruit citrus", FOOD),
      Emoji("🍋", "lemon fruit citrus sour", FOOD),
      Emoji("🍌", "banana fruit", FOOD),
      Emoji("🍍", "pineapple fruit", FOOD),
      Emoji("🥥", "coconut", FOOD),
      Emoji("🍎", "red apple fruit", FOOD),
      Emoji("🍏", "green apple fruit", FOOD),
      Emoji("🍐", "pear fruit", FOOD),
      Emoji("🍑", "peach fruit", FOOD),
      Emoji("🍒", "cherries fruit cherry", FOOD),
      Emoji("🍓", "strawberry fruit berry", FOOD),
      Emoji("🥝", "kiwi fruit", FOOD),
      Emoji("🍅", "tomato vegetable", FOOD),
      Emoji("🥑", "avocado", FOOD),
      Emoji("🍆", "eggplant aubergine vegetable", FOOD),
      Emoji("🥔", "potato vegetable", FOOD),
      Emoji("🥕", "carrot vegetable", FOOD),
      Emoji("🌽", "corn maize cob", FOOD),
      Emoji("🥒", "cucumber pickle", FOOD),
      Emoji("🥦", "broccoli vegetable", FOOD),
      Emoji("🍄", "mushroom toadstool", FOOD),
      Emoji("🥜", "peanuts nuts", FOOD),
      Emoji("🌰", "chestnut", FOOD),
      Emoji("🍞", "bread loaf", FOOD),
      Emoji("🥐", "croissant pastry", FOOD),
      Emoji("🥖", "baguette bread french", FOOD),
      Emoji("🥨", "pretzel", FOOD),
      Emoji("🥞", "pancakes breakfast", FOOD),
      Emoji("🧀", "cheese wedge", FOOD),
      Emoji("🍖", "meat on bone", FOOD),
      Emoji("🍗", "poultry leg chicken drumstick", FOOD),
      Emoji("🥩", "cut of meat steak", FOOD),
      Emoji("🥓", "bacon", FOOD),
      Emoji("🍔", "hamburger burger", FOOD),
      Emoji("🍟", "french fries chips", FOOD),
      Emoji("🍕", "pizza slice", FOOD),
      Emoji("🌭", "hot dog", FOOD),
      Emoji("🥪", "sandwich", FOOD),
      Emoji("🌮", "taco", FOOD),
      Emoji("🌯", "burrito wrap", FOOD),
      Emoji("🥙", "stuffed flatbread", FOOD),
      Emoji("🥚", "egg", FOOD),
      Emoji("🍳", "cooking fried egg pan", FOOD),
      Emoji("🥘", "shallow pan of food paella", FOOD),
      Emoji("🍲", "pot of food stew", FOOD),
      Emoji("🥣", "bowl with spoon cereal", FOOD),
      Emoji("🥗", "green salad", FOOD),
      Emoji("🍿", "popcorn", FOOD),
      Emoji("🥫", "canned food", FOOD),
      Emoji("🍱", "bento box", FOOD),
      Emoji("🍘", "rice cracker", FOOD),
      Emoji("🍙", "rice ball onigiri", FOOD),
      Emoji("🍚", "cooked rice", FOOD),
      Emoji("🍛", "curry rice", FOOD),
      Emoji("🍜", "steaming bowl ramen noodles", FOOD),
      Emoji("🍝", "spaghetti pasta", FOOD),
      Emoji("🍠", "roasted sweet potato", FOOD),
      Emoji("🍢", "oden", FOOD),
      Emoji("🍣", "sushi", FOOD),
      Emoji("🍤", "fried shrimp tempura prawn", FOOD),
      Emoji("🍥", "fish cake", FOOD),
      Emoji("🍡", "dango", FOOD),
      Emoji("🥟", "dumpling", FOOD),
      Emoji("🥠", "fortune cookie", FOOD),
      Emoji("🥡", "takeout box", FOOD),
      Emoji("🍦", "soft ice cream cone", FOOD),
      Emoji("🍧", "shaved ice", FOOD),
      Emoji("🍨", "ice cream", FOOD),
      Emoji("🍩", "doughnut donut", FOOD),
      Emoji("🍪", "cookie biscuit", FOOD),
      Emoji("🎂", "birthday cake", FOOD),
      Emoji("🍰", "shortcake slice cake", FOOD),
      Emoji("🥧", "pie", FOOD),
      Emoji("🍫", "chocolate bar", FOOD),
      Emoji("🍬", "candy sweet", FOOD),
      Emoji("🍭", "lollipop candy", FOOD),
      Emoji("🍮", "custard flan", FOOD),
      Emoji("🍯", "honey pot", FOOD),
      Emoji("🍼", "baby bottle milk", FOOD),
      Emoji("🥛", "glass of milk", FOOD),
      Emoji("☕", "hot beverage coffee tea", FOOD),
      Emoji("🍵", "teacup tea green", FOOD),
      Emoji("🍶", "sake", FOOD),
      Emoji("🍾", "bottle with popping cork champagne", FOOD),
      Emoji("🍷", "wine glass red", FOOD),
      Emoji("🍸", "cocktail glass martini", FOOD),
      Emoji("🍹", "tropical drink cocktail", FOOD),
      Emoji("🍺", "beer mug", FOOD),
      Emoji("🍻", "clinking beer mugs", FOOD),
      Emoji("🥂", "clinking glasses toast", FOOD),
      Emoji("🥃", "tumbler glass whisky", FOOD),
      Emoji("🥤", "cup with straw soda", FOOD),
      Emoji("🥢", "chopsticks", FOOD),
      Emoji("🥄", "spoon", FOOD),
      Emoji("🔪", "kitchen knife", FOOD),
      // ----- ACTIVITIES -----
      Emoji("⚽", "soccer ball football", ACTIVITIES),
      Emoji("🏀", "basketball", ACTIVITIES),
      Emoji("🏈", "american football", ACTIVITIES),
      Emoji("⚾", "baseball", ACTIVITIES),
      Emoji("🎾", "tennis", ACTIVITIES),
      Emoji("🏐", "volleyball", ACTIVITIES),
      Emoji("🏉", "rugby football", ACTIVITIES),
      Emoji("🎱", "pool 8 ball billiards", ACTIVITIES),
      Emoji("🏓", "ping pong table tennis", ACTIVITIES),
      Emoji("🏸", "badminton", ACTIVITIES),
      Emoji("🥅", "goal net", ACTIVITIES),
      Emoji("🏒", "ice hockey", ACTIVITIES),
      Emoji("🏑", "field hockey", ACTIVITIES),
      Emoji("🏏", "cricket game", ACTIVITIES),
      Emoji("⛳", "flag in hole golf", ACTIVITIES),
      Emoji("🎣", "fishing pole fish", ACTIVITIES),
      Emoji("🥊", "boxing glove", ACTIVITIES),
      Emoji("🥋", "martial arts uniform karate", ACTIVITIES),
      Emoji("🎽", "running shirt", ACTIVITIES),
      Emoji("🎿", "skis skiing", ACTIVITIES),
      Emoji("🛷", "sled sledding", ACTIVITIES),
      Emoji("🥌", "curling stone", ACTIVITIES),
      Emoji("🎯", "bullseye darts target", ACTIVITIES),
      Emoji("🎳", "bowling", ACTIVITIES),
      Emoji("🎮", "video game controller", ACTIVITIES),
      Emoji("🎰", "slot machine", ACTIVITIES),
      Emoji("🎲", "game die dice", ACTIVITIES),
      Emoji("🃏", "joker card", ACTIVITIES),
      Emoji("🀄", "mahjong", ACTIVITIES),
      Emoji("🎴", "flower playing cards", ACTIVITIES),
      Emoji("🎭", "performing arts theater masks", ACTIVITIES),
      Emoji("🎨", "artist palette painting art", ACTIVITIES),
      Emoji("🎬", "clapper board movie film", ACTIVITIES),
      Emoji("🎤", "microphone singing karaoke", ACTIVITIES),
      Emoji("🎧", "headphone music", ACTIVITIES),
      Emoji("🎼", "musical score", ACTIVITIES),
      Emoji("🎵", "musical note music", ACTIVITIES),
      Emoji("🎶", "musical notes music", ACTIVITIES),
      Emoji("🎹", "musical keyboard piano", ACTIVITIES),
      Emoji("🥁", "drum", ACTIVITIES),
      Emoji("🎷", "saxophone", ACTIVITIES),
      Emoji("🎺", "trumpet", ACTIVITIES),
      Emoji("🎸", "guitar", ACTIVITIES),
      Emoji("🎻", "violin", ACTIVITIES),
      Emoji("🎪", "circus tent", ACTIVITIES),
      Emoji("🏆", "trophy winner", ACTIVITIES),
      Emoji("🥇", "1st place medal gold", ACTIVITIES),
      Emoji("🥈", "2nd place medal silver", ACTIVITIES),
      Emoji("🥉", "3rd place medal bronze", ACTIVITIES),
      Emoji("🏅", "sports medal", ACTIVITIES),
      Emoji("🎫", "ticket", ACTIVITIES),
      Emoji("🎉", "party popper celebration", ACTIVITIES),
      Emoji("🎊", "confetti ball celebration", ACTIVITIES),
      Emoji("🎈", "balloon party", ACTIVITIES),
      Emoji("🎁", "wrapped gift present", ACTIVITIES),
      Emoji("🎀", "ribbon bow", ACTIVITIES),
      Emoji("🎆", "fireworks", ACTIVITIES),
      Emoji("🎇", "sparkler", ACTIVITIES),
      Emoji("✨", "sparkles shiny", ACTIVITIES),
      Emoji("🎐", "wind chime", ACTIVITIES),
      Emoji("🎑", "moon viewing ceremony", ACTIVITIES),
      Emoji("🎎", "japanese dolls", ACTIVITIES),
      Emoji("🎏", "carp streamer", ACTIVITIES),
      Emoji("🔮", "crystal ball fortune", ACTIVITIES),
      // ----- TRAVEL -----
      Emoji("🚗", "automobile car", TRAVEL),
      Emoji("🚕", "taxi cab", TRAVEL),
      Emoji("🚙", "sport utility vehicle suv", TRAVEL),
      Emoji("🚌", "bus", TRAVEL),
      Emoji("🚎", "trolleybus", TRAVEL),
      Emoji("🚓", "police car", TRAVEL),
      Emoji("🚑", "ambulance", TRAVEL),
      Emoji("🚒", "fire engine", TRAVEL),
      Emoji("🚐", "minibus van", TRAVEL),
      Emoji("🚚", "delivery truck", TRAVEL),
      Emoji("🚛", "articulated lorry truck", TRAVEL),
      Emoji("🚜", "tractor", TRAVEL),
      Emoji("🛴", "kick scooter", TRAVEL),
      Emoji("🛵", "motor scooter", TRAVEL),
      Emoji("🚲", "bicycle bike", TRAVEL),
      Emoji("🚨", "police car light siren", TRAVEL),
      Emoji("🚔", "oncoming police car", TRAVEL),
      Emoji("🚠", "mountain cableway", TRAVEL),
      Emoji("🚡", "aerial tramway", TRAVEL),
      Emoji("🚂", "locomotive steam train", TRAVEL),
      Emoji("🚄", "high speed train bullet", TRAVEL),
      Emoji("🚅", "bullet train", TRAVEL),
      Emoji("🚈", "light rail", TRAVEL),
      Emoji("🚝", "monorail", TRAVEL),
      Emoji("🚞", "mountain railway", TRAVEL),
      Emoji("🚋", "tram car", TRAVEL),
      Emoji("🚃", "railway car", TRAVEL),
      Emoji("🚇", "metro subway", TRAVEL),
      Emoji("🚉", "station", TRAVEL),
      Emoji("🛫", "airplane departure takeoff", TRAVEL),
      Emoji("🛬", "airplane arrival landing", TRAVEL),
      Emoji("🚀", "rocket launch space", TRAVEL),
      Emoji("🛸", "flying saucer ufo", TRAVEL),
      Emoji("🚁", "helicopter", TRAVEL),
      Emoji("🛶", "canoe kayak", TRAVEL),
      Emoji("⛵", "sailboat", TRAVEL),
      Emoji("🚤", "speedboat", TRAVEL),
      Emoji("🚢", "ship", TRAVEL),
      Emoji("⚓", "anchor", TRAVEL),
      Emoji("🚧", "construction sign", TRAVEL),
      Emoji("⛽", "fuel pump gas station", TRAVEL),
      Emoji("🚏", "bus stop", TRAVEL),
      Emoji("🗿", "moai statue easter island", TRAVEL),
      Emoji("🗽", "statue of liberty", TRAVEL),
      Emoji("🗼", "tokyo tower", TRAVEL),
      Emoji("🏰", "castle", TRAVEL),
      Emoji("🏯", "japanese castle", TRAVEL),
      Emoji("🎡", "ferris wheel", TRAVEL),
      Emoji("🎢", "roller coaster", TRAVEL),
      Emoji("🎠", "carousel horse", TRAVEL),
      Emoji("⛲", "fountain", TRAVEL),
      Emoji("⛺", "tent camping", TRAVEL),
      Emoji("🏠", "house", TRAVEL),
      Emoji("🏡", "house with garden", TRAVEL),
      Emoji("🏢", "office building", TRAVEL),
      Emoji("🏬", "department store", TRAVEL),
      Emoji("🏣", "japanese post office", TRAVEL),
      Emoji("🏥", "hospital", TRAVEL),
      Emoji("🏦", "bank", TRAVEL),
      Emoji("🏨", "hotel", TRAVEL),
      Emoji("🏪", "convenience store", TRAVEL),
      Emoji("🏫", "school", TRAVEL),
      Emoji("💒", "wedding chapel", TRAVEL),
      Emoji("⛪", "church", TRAVEL),
      Emoji("🕌", "mosque", TRAVEL),
      Emoji("🕍", "synagogue", TRAVEL),
      Emoji("🕋", "kaaba", TRAVEL),
      Emoji("🌁", "foggy", TRAVEL),
      Emoji("🌃", "night with stars", TRAVEL),
      Emoji("🌄", "sunrise over mountains", TRAVEL),
      Emoji("🌅", "sunrise", TRAVEL),
      Emoji("🌆", "cityscape at dusk", TRAVEL),
      Emoji("🌇", "sunset", TRAVEL),
      Emoji("🌉", "bridge at night", TRAVEL),
      Emoji("🌋", "volcano", TRAVEL),
      Emoji("🗻", "mount fuji", TRAVEL),
      Emoji("🌏", "globe asia earth", TRAVEL),
      Emoji("🌍", "globe europe africa earth", TRAVEL),
      Emoji("🌎", "globe americas earth", TRAVEL),
      Emoji("🌐", "globe with meridians", TRAVEL),
      Emoji("🗾", "map of japan", TRAVEL),
      Emoji("🌑", "new moon", TRAVEL),
      Emoji("🌓", "first quarter moon", TRAVEL),
      Emoji("🌕", "full moon", TRAVEL),
      Emoji("🌙", "crescent moon", TRAVEL),
      Emoji("🌛", "first quarter moon face", TRAVEL),
      Emoji("🌞", "sun with face", TRAVEL),
      Emoji("⭐", "star", TRAVEL),
      Emoji("🌟", "glowing star", TRAVEL),
      Emoji("🌠", "shooting star", TRAVEL),
      Emoji("🌈", "rainbow", TRAVEL),
      Emoji("⛅", "sun behind cloud", TRAVEL),
      Emoji("🌊", "water wave ocean", TRAVEL),
      Emoji("⛄", "snowman", TRAVEL),
      Emoji("🔥", "fire flame", TRAVEL),
      Emoji("💧", "droplet water", TRAVEL),
      Emoji("⚡", "high voltage lightning", TRAVEL),
      // ----- OBJECTS -----
      Emoji("⌚", "watch", OBJECTS),
      Emoji("📱", "mobile phone", OBJECTS),
      Emoji("💻", "laptop computer", OBJECTS),
      Emoji("💽", "computer disk", OBJECTS),
      Emoji("💾", "floppy disk save", OBJECTS),
      Emoji("💿", "optical disk cd", OBJECTS),
      Emoji("📀", "dvd", OBJECTS),
      Emoji("📷", "camera", OBJECTS),
      Emoji("📸", "camera with flash", OBJECTS),
      Emoji("📹", "video camera", OBJECTS),
      Emoji("🎥", "movie camera", OBJECTS),
      Emoji("📞", "telephone receiver", OBJECTS),
      Emoji("📟", "pager", OBJECTS),
      Emoji("📠", "fax machine", OBJECTS),
      Emoji("📺", "television tv", OBJECTS),
      Emoji("📻", "radio", OBJECTS),
      Emoji("⏰", "alarm clock", OBJECTS),
      Emoji("⌛", "hourglass done", OBJECTS),
      Emoji("⏳", "hourglass not done", OBJECTS),
      Emoji("📡", "satellite antenna", OBJECTS),
      Emoji("🔋", "battery", OBJECTS),
      Emoji("🔌", "electric plug", OBJECTS),
      Emoji("💡", "light bulb idea", OBJECTS),
      Emoji("🔦", "flashlight torch", OBJECTS),
      Emoji("💸", "money with wings", OBJECTS),
      Emoji("💵", "dollar banknote money", OBJECTS),
      Emoji("💴", "yen banknote money", OBJECTS),
      Emoji("💶", "euro banknote money", OBJECTS),
      Emoji("💷", "pound banknote money", OBJECTS),
      Emoji("💰", "money bag", OBJECTS),
      Emoji("💳", "credit card", OBJECTS),
      Emoji("💎", "gem stone diamond", OBJECTS),
      Emoji("🔧", "wrench", OBJECTS),
      Emoji("🔨", "hammer", OBJECTS),
      Emoji("🔩", "nut and bolt", OBJECTS),
      Emoji("🔫", "water pistol gun", OBJECTS),
      Emoji("💣", "bomb", OBJECTS),
      Emoji("🚬", "cigarette", OBJECTS),
      Emoji("📿", "prayer beads", OBJECTS),
      Emoji("💈", "barber pole", OBJECTS),
      Emoji("🔭", "telescope", OBJECTS),
      Emoji("🔬", "microscope", OBJECTS),
      Emoji("💊", "pill medicine", OBJECTS),
      Emoji("💉", "syringe shot", OBJECTS),
      Emoji("🚽", "toilet", OBJECTS),
      Emoji("🚿", "shower", OBJECTS),
      Emoji("🛁", "bathtub", OBJECTS),
      Emoji("🔑", "key", OBJECTS),
      Emoji("🚪", "door", OBJECTS),
      Emoji("🛒", "shopping cart trolley", OBJECTS),
      Emoji("📚", "books", OBJECTS),
      Emoji("📖", "open book", OBJECTS),
      Emoji("📝", "memo note writing", OBJECTS),
      Emoji("📌", "pushpin", OBJECTS),
      Emoji("📍", "round pushpin location", OBJECTS),
      Emoji("📎", "paperclip", OBJECTS),
      Emoji("🔒", "locked padlock", OBJECTS),
      Emoji("🔓", "unlocked padlock", OBJECTS),
      Emoji("🔗", "link", OBJECTS),
      Emoji("📦", "package box", OBJECTS),
      Emoji("📫", "closed mailbox", OBJECTS),
      Emoji("📮", "postbox", OBJECTS),
      Emoji("📅", "calendar date", OBJECTS),
      Emoji("📆", "tear off calendar", OBJECTS),
      Emoji("📊", "bar chart", OBJECTS),
      Emoji("📈", "chart increasing", OBJECTS),
      Emoji("📉", "chart decreasing", OBJECTS),
      Emoji("📋", "clipboard", OBJECTS),
      Emoji("📁", "file folder", OBJECTS),
      Emoji("📂", "open file folder", OBJECTS),
      Emoji("👑", "crown king queen", OBJECTS),
      Emoji("💍", "ring engagement", OBJECTS),
      Emoji("👓", "glasses", OBJECTS),
      Emoji("👔", "necktie", OBJECTS),
      Emoji("👕", "t shirt", OBJECTS),
      Emoji("👖", "jeans trousers", OBJECTS),
      Emoji("👗", "dress", OBJECTS),
      Emoji("👘", "kimono", OBJECTS),
      Emoji("👙", "bikini", OBJECTS),
      Emoji("👛", "purse", OBJECTS),
      Emoji("👜", "handbag", OBJECTS),
      Emoji("🎒", "backpack school", OBJECTS),
      Emoji("👞", "mans shoe", OBJECTS),
      Emoji("👟", "running shoe sneaker", OBJECTS),
      Emoji("👠", "high heeled shoe", OBJECTS),
      Emoji("👢", "womans boot", OBJECTS),
      Emoji("👒", "womans hat", OBJECTS),
      Emoji("🎩", "top hat", OBJECTS),
      Emoji("🎓", "graduation cap", OBJECTS),
      Emoji("📢", "loudspeaker", OBJECTS),
      Emoji("📣", "megaphone", OBJECTS),
      Emoji("🔔", "bell", OBJECTS),
      Emoji("🔕", "bell with slash muted", OBJECTS),
      // ----- SYMBOLS -----
      Emoji("🧡", "orange heart", SYMBOLS),
      Emoji("💛", "yellow heart", SYMBOLS),
      Emoji("💚", "green heart", SYMBOLS),
      Emoji("💙", "blue heart", SYMBOLS),
      Emoji("💜", "purple heart", SYMBOLS),
      Emoji("🖤", "black heart", SYMBOLS),
      Emoji("💔", "broken heart", SYMBOLS),
      Emoji("💕", "two hearts", SYMBOLS),
      Emoji("💞", "revolving hearts", SYMBOLS),
      Emoji("💓", "beating heart", SYMBOLS),
      Emoji("💗", "growing heart", SYMBOLS),
      Emoji("💖", "sparkling heart", SYMBOLS),
      Emoji("💘", "heart with arrow cupid", SYMBOLS),
      Emoji("💝", "heart with ribbon", SYMBOLS),
      Emoji("💟", "heart decoration", SYMBOLS),
      Emoji("💌", "love letter", SYMBOLS),
      Emoji("💤", "zzz sleep", SYMBOLS),
      Emoji("💢", "anger symbol", SYMBOLS),
      Emoji("💥", "collision boom", SYMBOLS),
      Emoji("💫", "dizzy", SYMBOLS),
      Emoji("💦", "sweat droplets", SYMBOLS),
      Emoji("💨", "dashing away", SYMBOLS),
      Emoji("🔯", "dotted six pointed star", SYMBOLS),
      Emoji("🕎", "menorah", SYMBOLS),
      Emoji("♈", "aries zodiac", SYMBOLS),
      Emoji("♉", "taurus zodiac", SYMBOLS),
      Emoji("♊", "gemini zodiac", SYMBOLS),
      Emoji("♋", "cancer zodiac", SYMBOLS),
      Emoji("♌", "leo zodiac", SYMBOLS),
      Emoji("♍", "virgo zodiac", SYMBOLS),
      Emoji("♎", "libra zodiac", SYMBOLS),
      Emoji("♏", "scorpio zodiac", SYMBOLS),
      Emoji("♐", "sagittarius zodiac", SYMBOLS),
      Emoji("♑", "capricorn zodiac", SYMBOLS),
      Emoji("♒", "aquarius zodiac", SYMBOLS),
      Emoji("♓", "pisces zodiac", SYMBOLS),
      Emoji("⛎", "ophiuchus zodiac", SYMBOLS),
      Emoji("🔱", "trident emblem", SYMBOLS),
      Emoji("📛", "name badge", SYMBOLS),
      Emoji("🔰", "japanese symbol for beginner", SYMBOLS),
      Emoji("⭕", "hollow red circle", SYMBOLS),
      Emoji("✅", "check mark button yes", SYMBOLS),
      Emoji("❎", "cross mark button", SYMBOLS),
      Emoji("❌", "cross mark no", SYMBOLS),
      Emoji("➕", "plus", SYMBOLS),
      Emoji("➖", "minus", SYMBOLS),
      Emoji("➗", "divide", SYMBOLS),
      Emoji("➰", "curly loop", SYMBOLS),
      Emoji("➿", "double curly loop", SYMBOLS),
      Emoji("❓", "question mark", SYMBOLS),
      Emoji("❔", "white question mark", SYMBOLS),
      Emoji("❕", "white exclamation mark", SYMBOLS),
      Emoji("❗", "exclamation mark", SYMBOLS),
      Emoji("🔅", "dim button", SYMBOLS),
      Emoji("🔆", "bright button", SYMBOLS),
      Emoji("🚸", "children crossing", SYMBOLS),
      Emoji("🚫", "prohibited no", SYMBOLS),
      Emoji("🚳", "no bicycles", SYMBOLS),
      Emoji("🚭", "no smoking", SYMBOLS),
      Emoji("🔞", "no one under eighteen", SYMBOLS),
      Emoji("📵", "no mobile phones", SYMBOLS),
      Emoji("🚱", "non potable water", SYMBOLS),
      Emoji("🚷", "no pedestrians", SYMBOLS),
      Emoji("🛑", "stop sign", SYMBOLS),
      Emoji("⛔", "no entry", SYMBOLS),
      Emoji("💯", "hundred points perfect", SYMBOLS),
      Emoji("🎦", "cinema", SYMBOLS),
      Emoji("📶", "antenna bars signal", SYMBOLS),
      Emoji("🔣", "input symbols", SYMBOLS),
      Emoji("🔤", "input latin letters", SYMBOLS),
      Emoji("♿", "wheelchair accessible", SYMBOLS),
      Emoji("🚹", "mens room", SYMBOLS),
      Emoji("🚺", "womens room", SYMBOLS),
      Emoji("🚻", "restroom", SYMBOLS),
      Emoji("🚼", "baby symbol", SYMBOLS),
      Emoji("🚾", "water closet wc", SYMBOLS),
      Emoji("🛂", "passport control", SYMBOLS),
      Emoji("🛃", "customs", SYMBOLS),
      Emoji("🛄", "baggage claim", SYMBOLS),
      Emoji("🛅", "left luggage", SYMBOLS),
      Emoji("🚮", "litter in bin", SYMBOLS),
      Emoji("🌀", "cyclone", SYMBOLS),
      Emoji("🔚", "end arrow", SYMBOLS),
      Emoji("🔙", "back arrow", SYMBOLS),
      Emoji("🔛", "on arrow", SYMBOLS),
      Emoji("🔜", "soon arrow", SYMBOLS),
      Emoji("🔝", "top arrow", SYMBOLS),
      Emoji("⬛", "black square", SYMBOLS),
      Emoji("⬜", "white square", SYMBOLS),
      Emoji("⚪", "white circle", SYMBOLS),
      Emoji("⚫", "black circle", SYMBOLS),
      Emoji("🔴", "red circle", SYMBOLS),
      Emoji("🔵", "blue circle", SYMBOLS),
      Emoji("🔶", "large orange diamond", SYMBOLS),
      Emoji("🔷", "large blue diamond", SYMBOLS),
      Emoji("🔸", "small orange diamond", SYMBOLS),
      Emoji("🔹", "small blue diamond", SYMBOLS),
      Emoji("🔺", "red triangle pointed up", SYMBOLS),
      Emoji("🔻", "red triangle pointed down", SYMBOLS),
      Emoji("💠", "diamond with a dot", SYMBOLS),
      Emoji("🔘", "radio button", SYMBOLS),
      Emoji("🔳", "white square button", SYMBOLS),
      Emoji("🔲", "black square button", SYMBOLS)
    )
}